# Generated by Django 2.2.6 on 2019-11-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=20, verbose_name='name of flight')),
                ('flight_aircompany', models.CharField(max_length=100, verbose_name='path to image of aircompany')),
                ('flight_initial_date', models.DateTimeField(verbose_name='date of departure')),
                ('flight_last_date', models.DateTimeField(verbose_name='date of arrival')),
                ('flight_initial_place', models.CharField(max_length=50, verbose_name='place of departure')),
                ('flight_last_place', models.CharField(max_length=50, verbose_name='place of arrival')),
                ('flight_rating', models.FloatField(verbose_name='rating of flight')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='text of review')),
                ('review_rating', models.FloatField(verbose_name='rating of review')),
                ('review_date', models.DateTimeField(verbose_name='date of review')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Altim.Flight')),
            ],
        ),
    ]
