# Generated by Django 2.2.6 on 2019-12-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_price',
            field=models.IntegerField(default=0, verbose_name='price of flight'),
            preserve_default=False,
        ),
    ]
