# Generated by Django 2.2.6 on 2019-12-09 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='rating of flight'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='rating of flight')),
                ('review_text', models.TextField()),
                ('review_image', models.ImageField(upload_to='review_imgs')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Altim.Flight')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
