# Generated by Django 2.2.6 on 2019-11-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='date_of_birth',
            field=models.DateField(verbose_name='date of birth'),
        ),
    ]
