# Generated by Django 2.2.6 on 2019-11-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_aircompany',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_price',
            field=models.IntegerField(default=0, verbose_name='price of flight'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_rating',
            field=models.FloatField(default=0.0, verbose_name='rating of flight'),
        ),
    ]
