# Generated by Django 2.2.6 on 2019-11-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0002_auto_20191122_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
