# Generated by Django 2.2.6 on 2019-11-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0002_auto_20191117_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_buy_date',
            field=models.DateTimeField(default=0, verbose_name='Date when flight was bought'),
        ),
    ]
