# Generated by Django 2.2.6 on 2019-11-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0002_auto_20191128_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_price',
        ),
    ]
