# Generated by Django 2.2.6 on 2019-11-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0003_remove_flight_flight_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_initial_date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_last_date',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_time',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
