# Generated by Django 2.2.6 on 2019-12-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0004_auto_20191204_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_name',
        ),
    ]
