# Generated by Django 2.2.6 on 2019-11-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0004_auto_20191128_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_initial_date',
            field=models.DateField(blank=True, null=True, verbose_name='date of departure'),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_initial_time',
            field=models.TimeField(blank=True, null=True, verbose_name='time of departure'),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_last_date',
            field=models.DateField(blank=True, null=True, verbose_name='date of arrival'),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_last_time',
            field=models.TimeField(blank=True, null=True, verbose_name='time of arrival'),
        ),
    ]
