# Generated by Django 2.2.6 on 2019-12-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0004_remove_review_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='plane_img',
            field=models.ImageField(default='default/airplane-silhouette.jpg', upload_to='plane_imgs/'),
        ),
    ]
