# Generated by Django 2.2.6 on 2019-11-21 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20191121_1913'),
        ('auth', '0011_update_proxy_permissions'),
        ('Altim', '0004_auto_20191117_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleUser',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
    ]
