# Generated by Django 2.2.6 on 2019-12-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0005_remove_ticket_ticket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='aircompany',
        ),
    ]
