# Generated by Django 2.2.6 on 2019-11-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0005_auto_20191128_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_name',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
