# Generated by Django 2.2.6 on 2019-11-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0005_auto_20191121_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
