# Generated by Django 2.2.6 on 2019-12-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Altim', '0006_remove_plane_aircompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
